version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: Nano3110
      MYSQL_DATABASE: satelite
      MYSQL_USER: alex
      MYSQL_PASSWORD: Nano3110
    volumes:
      - /cardsatelite_backend/.dbdata:/var/lib/mysql
    ports:
      - 3307:3306
